/* vactrol-core C ABI. Generated by cbindgen; do not edit by hand. */

#ifndef VACTROL_CORE_H
#define VACTROL_CORE_H

/* This file is auto-generated. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Default fingerprint seed. Mirrors Instruō's behaviour: the first instance is
 * always the same; the host assigns fresh seeds to later instances.
 */
#define DEFAULT_SEED 6215322990185237504

/**
 * Halfband FIR length. Must satisfy `LEN ≡ 1 (mod 4)` so the centre index is
 * even and the even polyphase phase reduces to a pure delay. Longer gives a
 * sharper transition and deeper stopband (better alias rejection) at more cost.
 */
#define HALFBAND_LEN 61

/**
 * Sample rate for all reference renders.
 */
#define SAMPLE_RATE 48000.0

/**
 * Length of each reference buffer (100 ms).
 */
#define CASE_LEN 4800

/**
 * Fixed seed for the imperfection reference case.
 */
#define REF_SEED 12648430

/**
 * One voice of the vactrol low-pass gate.
 */
typedef struct Lpg Lpg;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Create an LPG instance. Returns null on failure.
 *
 * # Safety
 * The returned pointer must be released with [`vactrol_lpg_destroy`].
 */
struct Lpg *vactrol_lpg_create(float sample_rate);

/**
 * Destroy an instance previously returned by [`vactrol_lpg_create`].
 *
 * # Safety
 * `ptr` must be a pointer from `vactrol_lpg_create` (or null), used at most once.
 */
void vactrol_lpg_destroy(struct Lpg *ptr);

/**
 * Set the sample rate.
 *
 * # Safety
 * `ptr` must be a valid instance pointer or null.
 */
void vactrol_lpg_set_sample_rate(struct Lpg *ptr, float sample_rate);

/**
 * Set runtime parameters. `mode`: 0 = Both, 1 = VCA, 2 = Lowpass.
 * `oversample`: 1, 2, or 4.
 *
 * # Safety
 * `ptr` must be a valid instance pointer or null.
 */
void vactrol_lpg_set_params(struct Lpg *ptr,
                            uint32_t mode,
                            float resonance,
                            float cv_offset,
                            float drive,
                            uint32_t oversample);

/**
 * Process one sample. Returns 0.0 on a null pointer or an (unexpected) panic.
 * Convenient for a host that drives audio one sample at a time (e.g. VCV Rack).
 *
 * # Safety
 * `ptr` must be a valid instance pointer or null.
 */
float vactrol_lpg_process_sample(struct Lpg *ptr, float audio_in, float cv_in);

/**
 * Process a block. `audio_in`, `cv_in`, and `out` must each point to `len` floats.
 *
 * # Safety
 * All pointers must be valid for `len` `f32`s (or null, in which case this is a
 * no-op), and `out` must be writable. `ptr` must be a valid instance pointer.
 */
void vactrol_lpg_process_block(struct Lpg *ptr,
                               const float *audio_in,
                               const float *cv_in,
                               float *out,
                               uintptr_t len);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* VACTROL_CORE_H */
