//! C ABI boundary for the C++ VCV adapter.
//!
//! Every entry point is panic-safe (`catch_unwind`) and allocation-free on the
//! audio thread (the create/destroy pair owns the only heap activity). The header
//! is generated by `cbindgen` (see `cbindgen.toml`); `Lpg` is an opaque pointer
//! on the C side.

use std::panic::{catch_unwind, AssertUnwindSafe};

use crate::params::{Mode, Params};
use crate::Lpg;

/// Create an LPG instance. Returns null on failure.
///
/// # Safety
/// The returned pointer must be released with [`vactrol_lpg_destroy`].
#[no_mangle]
pub extern "C" fn vactrol_lpg_create(sample_rate: f32) -> *mut Lpg {
    catch_unwind(|| Box::into_raw(Box::new(Lpg::new(sample_rate)))).unwrap_or(std::ptr::null_mut())
}

/// Destroy an instance previously returned by [`vactrol_lpg_create`].
///
/// # Safety
/// `ptr` must be a pointer from `vactrol_lpg_create` (or null), used at most once.
#[no_mangle]
pub unsafe extern "C" fn vactrol_lpg_destroy(ptr: *mut Lpg) {
    if ptr.is_null() {
        return;
    }
    let _ = catch_unwind(AssertUnwindSafe(|| drop(Box::from_raw(ptr))));
}

/// Set the sample rate.
///
/// # Safety
/// `ptr` must be a valid instance pointer or null.
#[no_mangle]
pub unsafe extern "C" fn vactrol_lpg_set_sample_rate(ptr: *mut Lpg, sample_rate: f32) {
    if ptr.is_null() {
        return;
    }
    let _ = catch_unwind(AssertUnwindSafe(|| {
        (*ptr).set_sample_rate(sample_rate);
    }));
}

/// Set runtime parameters. `mode`: 0 = Both, 1 = VCA, 2 = Lowpass.
/// `oversample`: 1, 2, or 4. `adaa`: 0 = off, nonzero = on.
///
/// # Safety
/// `ptr` must be a valid instance pointer or null.
#[no_mangle]
#[allow(clippy::too_many_arguments)]
pub unsafe extern "C" fn vactrol_lpg_set_params(
    ptr: *mut Lpg,
    mode: u32,
    resonance: f32,
    cv_offset: f32,
    drive: f32,
    oversample: u32,
    adaa: u32,
) {
    if ptr.is_null() {
        return;
    }
    let _ = catch_unwind(AssertUnwindSafe(|| {
        (*ptr).set_params(Params {
            mode: Mode::from_u32(mode),
            resonance,
            cv_offset,
            drive,
            oversample: oversample.min(4) as u8,
            adaa: adaa != 0,
        });
    }));
}

/// Process one sample. Returns 0.0 on a null pointer or an (unexpected) panic.
/// Convenient for a host that drives audio one sample at a time (e.g. VCV Rack).
///
/// # Safety
/// `ptr` must be a valid instance pointer or null.
#[no_mangle]
pub unsafe extern "C" fn vactrol_lpg_process_sample(
    ptr: *mut Lpg,
    audio_in: f32,
    cv_in: f32,
) -> f32 {
    if ptr.is_null() {
        return 0.0;
    }
    catch_unwind(AssertUnwindSafe(|| (*ptr).process_sample(audio_in, cv_in))).unwrap_or(0.0)
}

/// Process a block. `audio_in`, `cv_in`, and `out` must each point to `len` floats.
///
/// # Safety
/// All pointers must be valid for `len` `f32`s (or null, in which case this is a
/// no-op), and `out` must be writable. `ptr` must be a valid instance pointer.
#[no_mangle]
pub unsafe extern "C" fn vactrol_lpg_process_block(
    ptr: *mut Lpg,
    audio_in: *const f32,
    cv_in: *const f32,
    out: *mut f32,
    len: usize,
) {
    if ptr.is_null() || audio_in.is_null() || cv_in.is_null() || out.is_null() {
        return;
    }
    let _ = catch_unwind(AssertUnwindSafe(|| {
        let lpg = &mut *ptr;
        let audio = std::slice::from_raw_parts(audio_in, len);
        let cv = std::slice::from_raw_parts(cv_in, len);
        let out = std::slice::from_raw_parts_mut(out, len);
        lpg.process_block(audio, cv, out);
    }));
}
