/* S-Bank plugin C ABI. Generated by cbindgen; do not edit by hand. */

#ifndef S_BANK_H
#define S_BANK_H

/* This file is auto-generated. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * One voice of the vactrol low-pass gate.
 */
typedef struct Lpg Lpg;

/**
 * Opaque handle to one Strike voice (wraps the `strike-core` engine).
 */
typedef struct StrikeVoice StrikeVoice;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Create a Strike voice. Returns null on failure.
 *
 * # Safety
 * Release with [`strike_destroy`].
 */
struct StrikeVoice *strike_create(float sample_rate);

/**
 * Destroy a voice from [`strike_create`].
 *
 * # Safety
 * `ptr` must come from `strike_create` (or be null), used at most once.
 */
void strike_destroy(struct StrikeVoice *ptr);

/**
 * # Safety
 * `ptr` must be a valid voice or null.
 */
void strike_set_sample_rate(struct StrikeVoice *ptr, float sample_rate);

/**
 * Set knob params. `open`, `decay`, `material` are all `0..=1`.
 *
 * # Safety
 * `ptr` must be a valid voice or null.
 */
void strike_set_params(struct StrikeVoice *ptr, float open, float decay, float material);

/**
 * Configure the optional imperfection layer. `enabled`: 0 = off, nonzero = on.
 *
 * # Safety
 * `ptr` must be a valid voice or null.
 */
void strike_set_imperfection(struct StrikeVoice *ptr,
                             uint32_t enabled,
                             float noise_amp,
                             float drift_amount);

/**
 * Process one sample. `ctrl01` is the pre-EG opening in `0..1`; `decay_mod` is the
 * additive DECAY CV in `0..1` units; `hit_v` is the HIT trigger in volts. Feed a DC
 * value into `audio_in` (with no patched input) for a clean ping / envelope-out.
 * Returns 0.0 on a null pointer or panic.
 *
 * # Safety
 * `ptr` must be a valid voice or null.
 */
float strike_process_sample(struct StrikeVoice *ptr,
                            float audio_in,
                            float ctrl01,
                            float decay_mod,
                            float hit_v);

/**
 * Last gate-opening value `0..=1` (for an "openness" LED). 0.0 on null/panic.
 *
 * # Safety
 * `ptr` must be a valid voice or null.
 */
float strike_last_control(struct StrikeVoice *ptr);

/**
 * Create an LPG instance. Returns null on failure.
 *
 * # Safety
 * The returned pointer must be released with [`vactrol_lpg_destroy`].
 */
struct Lpg *vactrol_lpg_create(float sample_rate);

/**
 * Destroy an instance previously returned by [`vactrol_lpg_create`].
 *
 * # Safety
 * `ptr` must be a pointer from `vactrol_lpg_create` (or null), used at most once.
 */
void vactrol_lpg_destroy(struct Lpg *ptr);

/**
 * Set the sample rate.
 *
 * # Safety
 * `ptr` must be a valid instance pointer or null.
 */
void vactrol_lpg_set_sample_rate(struct Lpg *ptr, float sample_rate);

/**
 * Set runtime parameters. `mode`: 0 = Both, 1 = VCA, 2 = Lowpass.
 * `oversample`: 1, 2, or 4.
 *
 * # Safety
 * `ptr` must be a valid instance pointer or null.
 */
void vactrol_lpg_set_params(struct Lpg *ptr,
                            uint32_t mode,
                            float resonance,
                            float cv_offset,
                            float drive,
                            uint32_t oversample);

/**
 * Process one sample. Returns 0.0 on a null pointer or an (unexpected) panic.
 * Convenient for a host that drives audio one sample at a time (e.g. VCV Rack).
 *
 * # Safety
 * `ptr` must be a valid instance pointer or null.
 */
float vactrol_lpg_process_sample(struct Lpg *ptr, float audio_in, float cv_in);

/**
 * Process a block. `audio_in`, `cv_in`, and `out` must each point to `len` floats.
 *
 * # Safety
 * All pointers must be valid for `len` `f32`s (or null, in which case this is a
 * no-op), and `out` must be writable. `ptr` must be a valid instance pointer.
 */
void vactrol_lpg_process_block(struct Lpg *ptr,
                               const float *audio_in,
                               const float *cv_in,
                               float *out,
                               uintptr_t len);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* S_BANK_H */
