#!/usr/bin/env python3
"""Bake real font outlines into a pure-Python data file (fontdata.py).

Rack's nanosvg can't render <text>, so panel lettering must be vector geometry. The
stroke font looked thin next to other modules; this bakes the actual brand fonts
(Fira Code for labels, Space Grotesk for the masthead) to FILLED glyph outlines.

fonttools is only needed HERE (run once with the venv). The generator then imports the
baked fontdata.py — no font files, no fonttools at generation time.

Run:  /tmp/fontenv/bin/python tools/panelgen/bake_font.py   (cwd = tools/panelgen)

Glyphs are normalised so cap-height = 1 unit, baseline at y=0, y-DOWN — so the layout
in samefont.py only has to scale by the cap-height (mm) and translate to the baseline.
"""

from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.ttLib import TTFont

FONTS = {
    "MONO": "fonts/FiraCode-600.ttf",       # labels
    "DISP": "fonts/SpaceGrotesk-700.ttf",   # masthead / module title
}
CHARSET = [chr(c) for c in range(0x20, 0x7F)]  # printable ASCII


def bake(path: str) -> dict:
    t = TTFont(path)
    em = t["head"].unitsPerEm
    cap = getattr(t["OS/2"], "sCapHeight", 0) or int(em * 0.7)
    gs = t.getGlyphSet()
    cmap = t.getBestCmap()
    hmtx = t["hmtx"]
    s = 1.0 / cap  # normalise so cap-height = 1
    glyphs: dict[str, list] = {}
    for ch in CHARSET:
        gname = cmap.get(ord(ch))
        if gname is None:
            continue
        adv = round(hmtx[gname][0] * s, 4)
        pen = SVGPathPen(gs)
        # scale by 1/cap and flip y (-s): cap-height -> 1, baseline 0, glyph goes up
        gs[gname].draw(TransformPen(pen, (s, 0, 0, -s, 0, 0)))
        glyphs[ch] = [adv, pen.getCommands()]
    return {"glyphs": glyphs}


def main() -> None:
    data = {k: bake(v) for k, v in FONTS.items()}
    with open("fontdata.py", "w") as f:
        f.write("# Generated by bake_font.py — real-font glyph outlines, cap-normalised,\n")
        f.write("# y-down (cap-height = 1, baseline = 0). Do not edit; regenerate with\n")
        f.write("# /tmp/fontenv/bin/python bake_font.py. Fonts: Fira Code + Space Grotesk (OFL).\n")
        f.write("FONTDATA = ")
        f.write(repr(data))
        f.write("\n")
    print("wrote fontdata.py:", {k: len(v["glyphs"]) for k, v in data.items()}, "glyphs")


if __name__ == "__main__":
    main()
