"""S-Bank panel generator — the Sam-e visual system, as code.

A panel is declared ONCE (HP + a list of components: kind, mm position, label, and
the C++ widget enum id). From that single spec this emits two artifacts that can
never drift apart:

  * ``res/<Module>.svg``        — the brand-styled panel art (labels at the exact
                                  component positions).
  * ``src/<Module>_panel.inc``  — a C++ fragment of ``addParam/addInput/...`` calls
                                  the module's Widget constructor ``#include``s.

Brand rules baked in (Sam-e / S- signal system): NASA white / jet black / mission
gray environment, signal-state accents used sparingly, Space Grotesk + Fira Code,
registration crosshairs, a serial number, the ``S-`` mark, and "color is state".
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path

# --- brand kit -------------------------------------------------------------------
HP_MM = 5.08
PANEL_H = 128.5

INK = "#0B080B"          # jet black
PAPER = "#F5F5F1"        # NASA white
GRAY = "#A6A6A6"         # mission gray
ORANGE = "#FF5A00"       # signal / active
YELLOW = "#FFC400"       # energy
CYAN = "#19D2E5"         # information
EBLUE = "#1C46FF"        # depth
LABEL = "#c8c2f0"
DIM = "#9b93d6"
LINE = "#3a3560"
LINE2 = "#2c2748"

DISPLAY = "Space Grotesk, Helvetica, Arial, sans-serif"
MONO = "Fira Code, 'IBM Plex Mono', monospace"

# Component kind -> (Rack widget class, add-call). Lights carry their own template.
_PARAM = "addParam"
_INPUT = "addInput"
_OUTPUT = "addOutput"
_KINDS = {
    "knob": ("createParamCentered<RoundBlackKnob>", _PARAM, 8.0),
    "knob_sm": ("createParamCentered<RoundSmallBlackKnob>", _PARAM, 7.0),
    "trim": ("createParamCentered<Trimpot>", _PARAM, 5.0),
    "switch2": ("createParamCentered<CKSS>", _PARAM, 5.5),
    "switch3": ("createParamCentered<CKSSThree>", _PARAM, 5.5),
    "in": ("createInputCentered<PJ301MPort>", _INPUT, 6.5),
    "out": ("createOutputCentered<PJ301MPort>", _OUTPUT, 6.5),
}


@dataclass
class _Comp:
    kind: str
    x: float
    y: float
    eid: str               # C++ enum id, e.g. "A_OPEN_PARAM"
    label: str = ""
    accent: str | None = None   # label colour override
    light_tpl: str = "MediumLight<YellowLight>"


@dataclass
class Panel:
    module: str            # C++ module struct name, used to qualify enum ids
    title: str             # panel title (display)
    hp: int = 8
    serial: str = "001"
    comps: list[_Comp] = field(default_factory=list)
    notes: list[tuple[float, float, str, str]] = field(default_factory=list)  # x,y,text,cls
    dividers: list[float] = field(default_factory=list)

    @property
    def w(self) -> float:
        return self.hp * HP_MM

    # --- placement API (records a component + its label) -------------------------
    def _add(self, kind, x, y, eid, label="", accent=None, light_tpl=None):
        c = _Comp(kind, x, y, eid, label, accent)
        if light_tpl:
            c.light_tpl = light_tpl
        self.comps.append(c)

    def knob(self, x, y, eid, label="", small=False):
        self._add("knob_sm" if small else "knob", x, y, eid, label)

    def trim(self, x, y, eid, label=""):
        self._add("trim", x, y, eid, label)

    def switch(self, x, y, eid, label="", three=False):
        self._add("switch3" if three else "switch2", x, y, eid, label)

    def input(self, x, y, eid, label=""):
        self._add("in", x, y, eid, label)

    def output(self, x, y, eid, label=""):
        self._add("out", x, y, eid, label, accent=ORANGE)

    def light(self, x, y, eid, tpl="MediumLight<YellowLight>"):
        self._add("light", x, y, eid, light_tpl=tpl)

    def note(self, x, y, text, cls="sm"):
        self.notes.append((x, y, text, cls))

    def divider(self, y):
        self.dividers.append(y)

    # --- SVG emit ----------------------------------------------------------------
    def svg(self) -> str:
        w = self.w
        out: list[str] = []
        out.append('<?xml version="1.0" encoding="UTF-8"?>')
        out.append(
            f'<!-- Generated by tools/panelgen from the Sam-e panel system. '
            f'Do not edit by hand; edit the spec and regenerate. -->'
        )
        out.append(
            f'<svg xmlns="http://www.w3.org/2000/svg" version="1.1" '
            f'width="{w:.2f}mm" height="{PANEL_H}mm" viewBox="0 0 {w:.2f} {PANEL_H}">'
        )
        out.append(
            f'<defs><linearGradient id="bg" x1="0" y1="0" x2="0" y2="{PANEL_H}" '
            f'gradientUnits="userSpaceOnUse">'
            f'<stop offset="0" stop-color="#211d3a"/><stop offset="1" stop-color="#15131f"/>'
            f'</linearGradient><style>'
            f'text{{font-family:{MONO};fill:{LABEL};}}'
            f'.disp{{font-family:{DISPLAY};}}'
            f'.lbl{{font-size:1.9px;letter-spacing:.1px;}}'
            f'.sm{{font-size:1.6px;fill:{DIM};letter-spacing:.08px;}}'
            f'.tag{{font-size:2.4px;letter-spacing:.14px;}}'
            f'</style></defs>'
        )
        # background + border
        out.append(f'<rect x="0" y="0" width="{w:.2f}" height="{PANEL_H}" fill="url(#bg)"/>')
        out.append(
            f'<rect x="0.4" y="0.4" width="{w - 0.8:.2f}" height="{PANEL_H - 0.8}" '
            f'fill="none" stroke="{LINE}" stroke-width="0.3" rx="1.2"/>'
        )
        # registration crosshairs (tl, tr)
        for cx in (4.0, w - 4.0):
            out.append(
                f'<path d="M{cx - 1.4:.2f},{4.0} h2.8 M{cx:.2f},{2.6} v2.8" '
                f'stroke="{LINE}" stroke-width="0.25"/>'
            )
        # header: S-BANK · title · serial + signal LED
        out.append(
            f'<text x="7" y="7" class="disp tag" font-weight="700" fill="#e8e4ff">'
            f'S<tspan fill="{ORANGE}">-</tspan>BANK</text>'
        )
        out.append(
            f'<text x="{w - 7:.2f}" y="7" class="disp tag" font-weight="700" '
            f'text-anchor="end" fill="#e8e4ff">{self.title}</text>'
        )
        out.append(f'<line x1="7" y1="9" x2="{w - 7:.2f}" y2="9" stroke="{LINE}" stroke-width="0.25"/>')
        out.append(
            f'<text x="7" y="{PANEL_H - 3:.1f}" class="sm">SER {self.serial}</text>'
        )
        out.append(f'<circle cx="{w - 8:.2f}" cy="{PANEL_H - 3.5:.1f}" r="0.9" fill="{ORANGE}"/>')
        out.append(
            f'<text x="{w - 6.5:.2f}" y="{PANEL_H - 3:.1f}" class="sm">SIGNAL STABLE</text>'
        )
        out.append(
            f'<text x="{w / 2:.2f}" y="{PANEL_H - 3:.1f}" class="disp sm" '
            f'text-anchor="middle" font-weight="600">SAM-e</text>'
        )
        # dividers
        for y in self.dividers:
            out.append(f'<line x1="7" y1="{y}" x2="{w - 7:.2f}" y2="{y}" stroke="{LINE2}" stroke-width="0.25"/>')
        # free notes
        for (x, y, text, cls) in self.notes:
            out.append(f'<text x="{x:.2f}" y="{y:.2f}" class="{cls}" text-anchor="middle">{text}</text>')
        # component labels
        for c in self.comps:
            if c.kind == "light" or not c.label:
                continue
            off = _KINDS[c.kind][2]
            fill = f' fill="{c.accent}"' if c.accent else ""
            cls = "lbl" if c.kind in ("knob", "knob_sm") else "sm"
            out.append(
                f'<text x="{c.x:.2f}" y="{c.y - off:.2f}" class="{cls}"{fill} '
                f'text-anchor="middle">{c.label}</text>'
            )
        out.append("</svg>")
        return "\n".join(out) + "\n"

    # --- C++ placement fragment emit ---------------------------------------------
    def inc(self) -> str:
        lines = [
            f"// Generated by tools/panelgen from {self.module} spec. Do not edit; "
            f"regenerate.",
            f"// #include this inside the {self.module}Widget constructor.",
        ]
        for c in self.comps:
            # Always emit a decimal point so integer-valued coords are valid C++
            # float literals (e.g. "24.0f", not the invalid "24f").
            v = f"mm2px(Vec({c.x:.3f}f, {c.y:.3f}f))"
            eid = f"{self.module}::{c.eid}"
            if c.kind == "light":
                lines.append(
                    f"addChild(createLightCentered<{c.light_tpl}>({v}, module, {eid}));"
                )
            else:
                ctor, add, _ = _KINDS[c.kind]
                lines.append(f"{add}({ctor}({v}, module, {eid}));")
        return "\n".join(lines) + "\n"

    def write(self, svg_path: str | Path, inc_path: str | Path):
        Path(svg_path).write_text(self.svg())
        Path(inc_path).write_text(self.inc())
        print(f"  wrote {svg_path}")
        print(f"  wrote {inc_path}")
