"""Real-font panel lettering — drop-in for strokefont's API, but FILLED glyphs.

Renders text as filled `<path>` outlines from the baked brand fonts (fontdata.py:
Fira Code for labels, Space Grotesk for the masthead). Crisp and readable like other
Rack modules, still paths-only (nanosvg-safe). Pure Python — no fonttools at runtime;
fontdata.py is regenerated by bake_font.py.

Glyphs are cap-normalised (cap-height = 1, baseline = 0, y-down), so a label at cap
height `size` mm with baseline `y` just scales by `size` and translates to (cursor, y).
"""

from __future__ import annotations

import re

from fontdata import FONTDATA

_TOK = re.compile(r"[A-Za-z]|-?\d*\.?\d+(?:[eE][-+]?\d+)?")

# Axis pattern per absolute path command (SVGPathPen emits M/L/H/V/Q/C/Z). H is a lone
# x, V a lone y; the rest are x,y pairs. Honouring this is essential — treating H/V as
# pairs scrambles every following coordinate.
_AXIS = {
    "M": "xy", "L": "xy", "T": "xy",
    "Q": "xyxy", "S": "xyxy", "C": "xyxyxy",
    "H": "x", "V": "y", "Z": "",
}


def _font(display: bool) -> dict:
    return FONTDATA["DISP"] if display else FONTDATA["MONO"]


def _glyph(font: dict, ch: str):
    return font["glyphs"].get(ch) or font["glyphs"].get(" ") or [0.5, ""]


def text_width(s: str, size: float, tracking: float = 0.0, display: bool = False) -> float:
    """Width (mm) of ``s`` at cap height ``size`` (mm)."""
    g = _font(display)
    return sum(_glyph(g, ch)[0] * size + tracking for ch in s)


def _placed(d: str, scale: float, tx: float, ty: float) -> str:
    """Affine-transform an absolute SVG path (uniform scale + translate), command-aware
    so H/V single-axis commands don't break x/y parity."""
    toks = _TOK.findall(d)
    out: list[str] = []
    cmd = "M"
    j, n = 0, len(toks)

    def xf(tok: str, axis: str) -> str:
        v = float(tok)
        return f"{(tx + scale * v):.3f}" if axis == "x" else f"{(ty + scale * v):.3f}"

    while j < n:
        t = toks[j]
        if t[0].isalpha():
            cmd = t.upper()
            out.append(t)
            j += 1
            continue
        pat = _AXIS.get(cmd, "xy")
        if not pat:  # Z (or unknown) — no coords
            out.append(t)
            j += 1
            continue
        for axis in pat:  # one coordinate group; loop repeats for implicit repetition
            if j >= n or toks[j][0].isalpha():
                break
            out.append(xf(toks[j], axis))
            j += 1
    return " ".join(out)


def text_paths(s: str, x: float, y: float, size: float, color: str,
               anchor: str = "start", weight: float = 0.0, tracking: float = 0.0,
               display: bool = False) -> str:
    """Filled `<path>` markup for ``s``. ``(x, y)`` is the baseline; ``anchor`` ∈
    {start, middle, end}. ``weight`` is accepted for stroke-font API compatibility but
    ignored (the glyphs carry their own weight)."""
    g = _font(display)
    total = text_width(s, size, tracking, display)
    if anchor == "middle":
        x -= total / 2.0
    elif anchor == "end":
        x -= total
    cursor = x
    parts: list[str] = []
    for ch in s:
        adv, d = _glyph(g, ch)
        if d:
            parts.append(_placed(d, size, cursor, y))
        cursor += adv * size + tracking
    if not parts:
        return ""
    return f'<path d="{" ".join(parts)}" fill="{color}" fill-rule="nonzero"/>'
