#!/usr/bin/env bash
# Verify the C++ DSP port matches the Rust reference (components/ crates).
#
#   ./run_parity.sh            compile + check C++ output vs the committed goldens
#   ./run_parity.sh --bless    regenerate the Strike goldens from the Rust reference
#
# Vactrol goldens (testdata/golden/{pluck_both,vca_tone,lowpass_sweep}.json) come from
# `cargo run -p vactrol-harness -- bless`. Strike goldens (strike_*.json) come from the
# strike-core parity_dump example, regenerated by --bless here.
set -euo pipefail
cd "$(dirname "$0")"
ROOT="$(cd ../../.. && pwd)"
GOLD="$ROOT/testdata/golden"

if [[ "${1:-}" == "--bless" ]]; then
  for c in ping gated held; do
    cargo run -q -p strike-core --example parity_dump -- "$c" \
      | python3 -c "import sys,json; print(json.dumps([float(x) for x in sys.stdin.read().split()]))" \
      > "$GOLD/strike_$c.json"
    echo "blessed strike_$c.json"
  done
  exit 0
fi

BIN="${TMPDIR:-/tmp}/sbank_parity_$$"
trap 'rm -f "$BIN"' EXIT
c++ -std=c++11 -O2 -I ../src parity.cpp -o "$BIN"
python3 parity_check.py "$BIN"
